name: SheafEnv
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip=23.3
  - numpy<2.0
  
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  
  - pyg=2.4.0
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  
  - pip:
      - torch-householder
      - tqdm
      - pandas
      - numpy
      - shap
      - gurobipy
      - pytest
      - wandb
      - torchdiffeq
      - networkx
      - xlrd
      - xgboost
      - lightgbm
      - aif360
      - optuna
      - sqlalchemy
      - tensorflow
      - torchmetrics